
SELECT ROUND((SYSDATE - (   TO_DATE(:log_time ,'YYYYMMDDHI24HISS') + NUMTODSINTERVAL(:sec, 'SECOND'))) * 24 * 60 * 60)  FROM DUAL;
SELECT CAST(SYSTIMESTAMP + NUMTODSINTERVAL(:sec, 'SECOND') AS TIMESTAMP) FROM DUAL;


