/* 임시 테이블 생성 */
CREATE PRIVATE TEMPORARY TABLE ORA$PTT_CALC_ELEMENTS_TEMP (
    RPT_ACCC VARCHAR2(20),  -- 보고 계정 코드
    SIGN_CD CHAR(1),         -- 부호
    REF_RPT_ACCC VARCHAR2(100),  -- 참조 보고 계정 코드
    LVL NUMBER               -- 계층 레벨
);

/* 임시 테이블에 데이터 삽입 */
INSERT INTO ORA$PTT_CALC_ELEMENTS_TEMP (RPT_ACCC, SIGN_CD, REF_RPT_ACCC, LVL)
SELECT
    RPT_ACCC,
    CASE
        WHEN LEVEL = 1 THEN NULL
        ELSE SUBSTR(REGEXP_SUBSTR(CLC_FML_CNTN, '([+-]?[^+-]+)', 1, LEVEL), 1, 1)
    END,    
    CASE
        WHEN LEVEL = 1 THEN TRIM(SUBSTR(REGEXP_SUBSTR(CLC_FML_CNTN, '([+-]?[^+-]+)', 1, LEVEL), 1))
        ELSE TRIM(SUBSTR(REGEXP_SUBSTR(CLC_FML_CNTN, '([+-]?[^+-]+)', 1, LEVEL), 2))
    END,
    LEVEL
FROM
    ISR_RPTG_DATA
CONNECT BY
    PRIOR RPT_ACCC = RPT_ACCC
    AND PRIOR SYS_GUID() IS NOT NULL
    AND LEVEL <= REGEXP_COUNT(CLC_FML_CNTN, '[^+-]+')
;    


/* *******************  임시 테이블 확인 */
SELECT * FROM ORA$PTT_CALC_ELEMENTS_TEMP;

/* *******************  임시 테이블 확인 */
SELECT
    CE.RPT_ACCC,
    CE.SIGN_CD,
    CE.REF_RPT_ACCC,
    GL.AMT ,
    GL.RPT_ACCC
FROM
    ORA$PTT_CALC_ELEMENTS_TEMP CE
    JOIN GENERAL_LEDGER GL ON CE.REF_RPT_ACCC = GL.RPT_ACCC
ORDER BY    CE.RPT_ACCC , CE.LVL
;

/* *******************  */
/* 계산된 금액을 저장할 임시 테이블 생성 */
CREATE PRIVATE TEMPORARY TABLE ORA$PTT_AGGREGATED_AMOUNTS_TEMP (
    RPT_ACCC VARCHAR2(20),  -- 보고 계정 코드
    CALCULATED_AMOUNT NUMBER -- 계산된 금액
);

/* 임시 테이블에 계산된 금액 삽입 */
INSERT INTO ORA$PTT_AGGREGATED_AMOUNTS_TEMP (RPT_ACCC, CALCULATED_AMOUNT)
SELECT
    CE.RPT_ACCC,
    SUM(CASE
        WHEN CE.SIGN_CD = '-' THEN -GL.AMT 
        ELSE GL.AMT 
    END) AS CALCULATED_AMOUNT
FROM
    ORA$PTT_CALC_ELEMENTS_TEMP CE
    JOIN GENERAL_LEDGER GL ON CE.REF_RPT_ACCC = GL.RPT_ACCC
GROUP BY
    CE.RPT_ACCC;
    

/* *******************  임시 테이블 확인 */
SELECT * FROM ORA$PTT_AGGREGATED_AMOUNTS_TEMP ORDER BY RPT_ACCC	;
    

/* 최종 결과를 저장할 임시 테이블 생성 */
CREATE PRIVATE TEMPORARY TABLE ORA$PTT_FINAL_RESULTS_TEMP (
    RPT_ACCC VARCHAR2(20),  -- 보고 계정 코드
    FINAL_AMOUNT NUMBER      -- 최종 금액
);


/* 최종 결과를 임시 테이블에 삽입 */
INSERT INTO ORA$PTT_FINAL_RESULTS_TEMP (RPT_ACCC, FINAL_AMOUNT)
SELECT
    E.RPT_ACCC,
    SUM(CASE
        WHEN E.SIGN_CD = '-' THEN -1 * A.CALCULATED_AMOUNT
        ELSE A.CALCULATED_AMOUNT
    END) AS FINAL_AMOUNT
FROM
    ORA$PTT_CALC_ELEMENTS_TEMP E
    INNER JOIN ORA$PTT_AGGREGATED_AMOUNTS_TEMP A ON E.REF_RPT_ACCC = A.RPT_ACCC
GROUP BY
    E.RPT_ACCC;


/* 최종 결과 선택 */
SELECT
    F.RPT_ACCC,        -- 보고 계정 코드
    F.FINAL_AMOUNT     -- 최종 금액
FROM
    ORA$PTT_FINAL_RESULTS_TEMP F
ORDER BY
    F.RPT_ACCC;
    
/* 롤백 */
ROLLBACK; -- 작업 취소 및 임시 테이블 삭제
