-- [1] SYSTIMESTAMP에 N초 더하기 (:add_sec 바인드)
SELECT
    CAST(SYSTIMESTAMP + NUMTODSINTERVAL(:add_sec, 'SECOND') AS TIMESTAMP)
FROM
    DUAL;

-- [2] SYSTIMESTAMP에 N시간 더하기 (:add_hour 바인드)
SELECT
    CAST(SYSTIMESTAMP + NUMTODSINTERVAL(:add_hour, 'HOUR') AS TIMESTAMP) AS ADD_HOUR
FROM
    DUAL;

-- [3] SYSTIMESTAMP에 N분 더하기 (:add_min 바인드)
SELECT
    CAST(SYSTIMESTAMP + NUMTODSINTERVAL(:add_min, 'MINUTE') AS TIMESTAMP) AS ADD_MIN
FROM
    DUAL;

-- [4] SYSDATE에 N초 더하기 (:add_sec 바인드)
SELECT
    SYSDATE + NUMTODSINTERVAL(:add_sec, 'SECOND') AS ADD_SEC
FROM
    DUAL;

-- [5] SYSDATE에 N시간 더하기 (:add_hour 바인드)
SELECT
    SYSDATE + NUMTODSINTERVAL(:add_hour, 'HOUR') AS ADD_HOUR
FROM
    DUAL;

-- [6] SYSDATE에 N분 더하기 (:add_min 바인드)
SELECT
    SYSDATE + NUMTODSINTERVAL(:add_min, 'MINUTE') AS ADD_MIN
FROM
    DUAL;

