SELECT CAST(SYSTIMESTAMP + NUMTODSINTERVAL(60, 'SECOND') AS TIMESTAMP) FROM DUAL;

SELECT ROUND((SYSDATE - (   TO_DATE(LOG_TIME,'YYYYMMDDHI24HISS') + NUMTODSINTERVAL(60, 'SECOND'))) * 24 * 60 * 60)
  FROM DUAL;


